hwi_oauth:
  # list of names of the firewalls in which this bundle is active, this setting MUST be set
  firewall_names: [main]

  # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
  resource_owners:
    facebook:
      type: facebook
      client_id: "427095729440722%"
      client_secret: "363dc94d05916d4330b6a2b0c4f31de5"
      scope: "email"
      options:
        display: popup
        csrf: true
    google:
      type: google
      client_id: 614795717832-t7ch0vm7bh4aq5od1u2d7sgeb2prg4e6.apps.googleusercontent.com
      client_secret: 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
      options:
        access_type: offline
