knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    github:
      type: github
      client_id: "%env(GITHUB_ID)%"
      client_secret: "%env(GITHUB_SECRET)%"
      redirect_route: oauth_check
      redirect_params:
        service: github
    google:
      type: google
      client_id: 614795717832-t7ch0vm7bh4aq5od1u2d7sgeb2prg4e6.apps.googleusercontent.com
      client_secret: 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
      options:
        access_type: offline
      redirect_route: oauth_check
      redirect_params:
        service: google
