#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix: /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
  prefix: /connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  prefix: /login

#facebook_login:
#  path: /login/check-facebook
custom_login:
  path: /login/check-custom

github_login:
  path: /login/check-github

oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController

connect_google_check:
  path: /login/check-google

connect_facebook_check:
  path: /login/check-facebook
